name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  # Use the role ARN from secrets
          role-session-name: GitHubActionsSession
          aws-region: ${{ secrets.AWS_REGION }}         # Specify your AWS region

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.0
        

    - name: Run Destroy Script
      run: |
        terraform init
        terraform destroy
